### ISSUE TITLE
Issue with the demo_impedance_ctrl_python.py 

### ISSUE THREAD

**Issue by thathvik** [machines-in-motion/mim_control#18]
There is an error observed while calling the Impedance Controller in the demo file. The Impedance Controller takes 6 attributes, which were not called in this file (line 32).

**Comment by MaximilienNaveau** [comment]
Can you give us the name of the file?

**Comment by thathvik** [comment]
Hi Max, 

The name of the file I was talking about is demo_impedance_ctrl_python.py, it is located in the demos folder.

I have implemented the same system, semi successfully using the following line of code.

`ctrls = [ImpedanceController(name[i], pin_robot, root_names[i], endeff_names[i], 6 , [0,1,2,3,4,5,6,7]) for i in range(len(endeff_names))]`

**Comment by MaximilienNaveau** [comment]
ok thanks,
I strongly suggest you have a look a the `demo_XXX_cpp.py` they refer to the python bindings and is therefore much more tested and we do run it on our robots.
The demo on the python one is referring to pure python implementation which is kinda deprecated...

In the future I will remove the pure python code in favor of the C++ bindings, sorry for the misleading code.
